
# 用户服务
server:
  port: 8080
security:
  basic:
    enabled: false # 暂时关闭安全认证

ali:
  ssm:
    accessKeyId: 123456 # 阿里云短信id
    accessKeySecret: 222222 # 阿里云短信密码
wx:
  open:
    appid: aaaaaa # 微信开发者的appid方式
    secretKey: aaaaaaaaaaaaa # 微信开发者密码方式
management:
  security:
    enabled: false # 暂时关闭安全认证
#   context-path: /example
# user: 
#   admin: 
#     name: hello
#     role: admin
#数据库设置
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sportbean?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    # password: 123456
    password: root
#下面为连接池补充设置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间   
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒 
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    fileters: stat,wall,log4j
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据 
    useGlobalDataSourceStat: true
    maxPoolPreparedStatementParConnectionSize: 20


# mybase认真
# mybatis:
#   mapper-locations: classpath*:com/sportbean/wx/mapper/*.xml
#   check-config-location: true
#   type-aliases-package: com.sportbean.wx.pojo
# mybatis:
#     configLocation: classpath:mybatis.xml              #mybatis配置文件路径
#     mapperLocations: classpath:mapper/**/*.xml  #所有mapper映射文件地址
#     check-config-location: true
#     type-aliases-package: com.sportbean.wx.pojo